numeros = []
numero = int(input('Informe o numero: '))
numeros.append(numero)
numero = int(input('Informe o numero: '))
numeros.append(numero)
numero = int(input('Informe o numero: '))
numeros.append(numero)
numero = int(input('Informe o numero: '))
numeros.append(numero)
numero = int(input('Informe o numero: '))
numeros.append(numero)
print(numero)